apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebdeployment
  labels:
    app: srinuwaps
spec:
  replicas: 6
  selector:
    matchLabels:
      app: srinuwaps
  template:
    metadata:
      labels:
        app: srinuwaps
    spec:
      containers:
      - name: myweb
        image: kammana/myweb:"$(version)"
        ports:
        - containerPort: 8080
